services:
  db:
    image: docker.io/mariadb:10.11
    container_name: ${THEME_SLUG:-meros-wp}_dev_db
    environment:
      MARIADB_DATABASE: ${DB_NAME:-wordpress}
      MARIADB_USER: ${DB_USER:-dbuser}
      MARIADB_PASSWORD: ${DB_PASSWORD:-dbpassword}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${THEME_SLUG:-meros-wp}_dev_wordpress
    ports:
      - ${WP_PORT:-8000}:80
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: docker.io/phpmyadmin
    container_name: ${THEME_SLUG:-meros-wp}_dev_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT:-9000}:80
    environment:
      PMA_HOST: db

volumes:
  db_data: